Order page
hekto-shop/hektoMent pull request #29
Opened 2022-02-28 22:14 UTC by levan-ted

Order form. 

1. Send order details to Firestore 'orders' collection, 
2. Update user's budget in firestore 'users' collection, 

Order can't be submitted if User has no enough balance.

2022-03-01 11:39 UTC, sabamamasakhlisi requested changes

2022-03-01 11:39 UTC, sabamamasakhlisi commented on src/components/CartItems/CartItems.js
> +  const productList = cartItems.map((product) => {
ProductItem - ად შეგვიძლია გატანა

2022-03-01 11:39 UTC, sabamamasakhlisi commented on src/components/CartItems/CartItems.js
> +            <div
quantityhandler შეგვიძლია კომპონენტად

2022-03-02 09:10 UTC, levan-ted commented on src/components/CartItems/CartItems.js
> +  const productList = cartItems.map((product) => {
გავიტანე

2022-03-02 09:11 UTC, levan-ted commented on src/components/CartItems/CartItems.js
> +            <div
ძალიან ბევრი Props Drilling გამოდის და ხომ არ დავტოვოთ? ProductItem კომპონენტში გავიტანე ესეც და მეტნაკლებად წაკითხვადი არის

2022-03-02 10:53 UTC, sabamamasakhlisi approved these changes

2022-03-02 10:53 UTC, merged